# Generated by Django 4.0.10 on 2023-12-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
